### ISSUE TITLE
inconsistent implementation of styled props for hd.tooltip

### ISSUE THREAD

**Issue by tkriplean** [hyperdiv/hyperdiv#48]
**Describe the bug**
hd.tooltip implements Styled but has some inconsistent styling applied. For example:
- Setting 'width' doesn't change the tooltip's width, but does set the width of the content the tooltip definition wraps. 
- Whereas 'font_size' and 'background_color' have no impact. 

I had been expecting to be able to customize the appearance of the tooltip. 

This is a very low priority issue from my perspective, just noting it. 

**To Reproduce**
```
with hd.tooltip("hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello ", 
                            font_size="x-large", width=5, background_color="red-500"):
      with hd.box():
           hd.text("my width has been determined...by a tooltip?!?!?! How dare it!")
```

**Comment by mariusnita** [comment]
I'll look into how to make this more ergonomic and better documented but I think you want this:

```py
def main():
    with hd.tooltip(
        "hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello ",
        # style the tooltip body
        body_style=hd.style(
            font_size="x-large",
            width=5,
            background_color="red-500",
        ),
        # style the tooltip arrow
        base_arrow_style=hd.style(background_color="red-500"),
    ):
        with hd.box():
            hd.text("my width has been determined...by a tooltip?!?!?! How dare it!")
```

I think being able to style the tooltip container itself probably doesn't make sense, so it probably shouldn't inherit from `Styled`.

**Comment by mariusnita** [comment]
I think the unintuitive part here is that `hd.tooltip()` is not the actual popup, it's an "activation container" within which you can put components. When you mouse over the activation container, the actual popup container is made visible.

I think I will leave `Styled` as a base class because in some niche cases it does make sense to style that container. I can think of having to set `width`/`grow`/`basis` to control layout when nesting tooltip'd components in boxes.

The main bug here is incomplete documentation I think.
