### ISSUE TITLE
inifinite loop not expected trying to count reloads

### ISSUE THREAD

**Issue by alon** [hyperdiv/hyperdiv#64]
**Describe the bug**
I was trying to get an indicator of how many times the main function was evaluated, and I ran into the app_runner.run limit of 20, expecting only a single call.

I see now how hyperdiv is looking for changes and the "state.x += 1" is always producing one. I guess you could special case a "only state changes" but of course that would not be helpful.

Perhaps this is something that should be documented? I understand I'm doing something that is not helpful (except for maybe screen savers).

I expect I would run into the same issue with "state.x = time()" or any random source.

**To Reproduce**
Run this
```python
import hyperdiv as hd

def main():
    state = hd.state(x=0)
    state.x += 1
    hd.text(f"{state.x}")

hd.run(main)
```

**Context**
Trying to learn about hyperdiv, came here from hackernews reading about the http braid extension, and having played with marimo.io for a similar use case I thought I'd checkout hyperdiv :) Seems really cool so far, just wanted to report this.

**Comment by mariusnita** [comment]
Hi. Yes this is expected behavior. It should probably be documented more explicitly. It is hinted at here: https://docs.hyperdiv.io/guide/state#change-detection

> Hyperdiv re-runs the app when a prop's value is mutated to a different value.

In this case the app is mutated to a new value every time and re-runs indefinitely so Hyperdiv stops what would otherwise be an infinite loop.

You could do a hacky/for fun thing and use a global Python variable to count runs.

```py
runs = 0

def main():
    global runs

    runs += 1

    s = hd.state(count=0)
    if hd.button("Click!").clicked:
        s.count += 1

    hd.text(f"Runs: {runs}")

hd.run(main)
```

This counts runs across all connections.

You can also print/log stuff in the main function, of course.
