### ISSUE TITLE
Dev dependencies block install

### ISSUE THREAD

**Issue by fliepeltje** [hyperdiv/hyperdiv#8]
I wanted to try this out in an existing project and got an error:

```bash
hyperdiv (0.1.1) depends on black (>=22.6.0,<23.0.0), hyperdiv (>=0.1.1,<0.2.0) requires black (>=22.6.0,<23.0.0)
```

I checked out the [pyproject.toml](https://github.com/hyperdiv/hyperdiv/blob/main/pyproject.toml) and saw `black` (but also stuff like `pygments`) in the regular dependencies. Could you move the dev dependencies into their respective section? :)

**Comment by mariusnita** [comment]
Hi! I don't understand that error at a glance. Is it because you have a different version of black already installed in that virtualenv?

Black is currently listed as a regular dependency because the Hyperdiv docs app imports black and uses it to format code. I believe I can easily make black a dev dependency though. Pygments is a regular dependency, it is used to syntax highlight markdown code blocks.

**Comment by fliepeltje** [comment]
> Is it because you have a different version of black already installed in that virtualenv?

That's exactly right :)
I think most people will have black installed as a dev dependency, so if it is not essential to the functionality app it would be great to move it to dev I think :)

Did not realize you used pygments in the app for that, so disregard that comment!

**Comment by mariusnita** [comment]
Makes sense, I'll work on moving black to dev dependencies, I think it's an easy fix.

**Comment by mariusnita** [comment]
I moved black to dev dependencies in v0.1.2
